language: php

php:
  - 5.3
  - 5.4
  - 5.5


notifications:
  email:
    - gjero@krsteski.de
    
before_script:
    - "[ ! -d ~/.composer ] && mkdir ~/.composer || true"
    - "[ ! -z $GITHUB_TOKEN ] && echo \"{ \\\"config\\\": { \\\"github-oauth\\\": { \\\"github.com\\\": \\\"$GITHUB_TOKEN\\\" } } }\" > ~/.composer/config.json || true"
    - wget http://getcomposer.org/composer.phar
    - "[ ! -z $GITHUB_TOKEN ] && php composer.phar install --dev || php composer.phar install --dev --prefer-source"

script:
    - bin/atoum --test-all
